<?php

echo $this->inlineScript()->prependFile($this->basePath(). '/js/datehelper.js');
$url = $this->url('concedente', ['controller' => 'local', 'action' => 'cadastrar']);

?>
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Editar Local</h4>
                </div>
                <div class="content">
                   <form method="post" action="<?= $url; ?>">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Logradouro</label>
                                    <input type="text" class="form-control border-input" placeholder="Home Address" name="logradouro">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                             <div class="col-md-6">
                                <div class="form-group">
                                    <label>Bairro</label>
                                    <input type="text" class="form-control border-input" placeholder="senha" name="bairro">
                                </div>
                            </div>   
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Município</label>
                                    <input type="text" class="form-control border-input" placeholder="City"
                                          name="municipio">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>UF</label>
                                    <input type="text" class="form-control border-input" placeholder="Country"
                                           name="uf">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>CEP</label>
                                    <input type="number" class="form-control border-input" name="cep">
                                </div>
                            </div>
                        </div>
                        </div>
                            <div class="text-center ">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">Cadastrar</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>