<?php
$url = $this->url('concedente', ['controller' => 'local', 'action' => 'cadastrar']);

?>
<div class="container-fluid">
    <div class="col-lg-12 col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">Cadastrar Local</h4>
            </div>
            <div class="content">
                <form method="post" action="<?= $url; ?>">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Logradouro</label>
                                <input type="text" class="form-control border-input" placeholder="Ex: Rua Feliz" name="logradouro" required>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>Número</label>
                                <input type="text" class="form-control border-input" placeholder="Ex: 143" name="numero" required>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Complemento</label>
                                <input type="text" class="form-control border-input" placeholder="Ex: Perto do Shopping" name="complemento" required>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="form-group">
                                <label>CEP</label>
                                <input type="number" class="form-control border-input" placeholder="Ex: 30450650" name="cep" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Bairro</label>
                                <input type="text" class="form-control border-input" placeholder="Ex: Jardins" name="bairro" required>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>Município</label>
                                <input type="text" class="form-control border-input" placeholder="Ex: Belo Horizonte" name="municipio" required>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label>UF</label>
                                <input type="text" class="form-control border-input" placeholder="Ex: Minas Gerais" name="uf" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                       <div class="col-md-4">
                        <div class="form-group">
                            <label>Area</label>
                            <input type="text" class="form-control border-input" placeholder="Ex: 1000" name="areaLocal" required>
                        </div>
                    </div>


                    <div class="col-md-7">
                        <div class="form-group">
                          <label>Selecione os tipos de Mudas: </label>      
                          <select id="example-getting-started" multiple="multiple" required>
                            <?php

                            foreach ($mudas as $muda){
                                $dadosMuda=explode('-', $muda->TipoMudaToString());
                                echo "<option value='$dadosMuda[0]'>".$dadosMuda[1].'-'.$dadosMuda[2]. "</option>";
                            }
                            ?>
                        </select>
                    </div> 
                </div>
            </div>  
        </div>

        <div class="row" style="display: none;">
          <div class="col-md-12">
            <div class="form-group">
              <input type="text" name="tiposMudaLocal"/>
          </div>
      </div>
  </div>


  <div class="text-center">
    <button type="submit" class="btn btn-info btn-fill btn-wd">Cadastrar</button>
</div>
<div class="clearfix"></div>
</form>
</div>
</div>
</div>
</div>

<script type="text/javascript">

    var arraysMudas=[];

    $(document).ready(function() {
        $('#example-getting-started').multiselect({
            enableFiltering: true,
            filterPlaceholder: 'Search',

            onChange: function(element, checked) {
                if (checked === true) {
                    arraysMudas.push(element.val());
                    $("input[name='tiposMudaLocal']").val(arraysMudas.join('-'));
                }
                else if (checked === false) {
                   var indice=arraysMudas.indexOf(element.val());
                   arraysMudas.splice(indice,1);
                   $("input[name='tiposMudaLocal']").val(arraysMudas.join('-'));
               }
           }

       });
    });
</script>

