<?php

echo $this->inlineScript()->prependFile($this->basePath(). '/js/datehelper.js');
$url = $this->url('concedente', ['controller' => 'local', 'action' => 'cadastrar']);

?>
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Cadastrar Local</h4>
                </div>
                <div class="content">
                   <form method="post" action="<?= $url; ?>">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Logradouro</label>
                                    <input type="text" class="form-control border-input" placeholder="Ex: Rua Feliz" name="logradouro">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Número</label>
                                    <input type="text" class="form-control border-input" placeholder="Ex: 143" name="numero">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Complemento</label>
                                    <input type="text" class="form-control border-input" placeholder="Ex: Perto do Shopping" name="complemento">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                             <div class="col-md-4">
                                <div class="form-group">
                                    <label>Bairro</label>
                                    <input type="text" class="form-control border-input" placeholder="Ex: Jardins" name="bairro">
                                </div>
                            </div>   
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Município</label>
                                    <input type="text" class="form-control border-input" placeholder="Ex: Belo Horizonte" name="municipio">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>UF</label>
                                    <input type="text" class="form-control border-input" placeholder="Ex: Minas Gerais" name="uf">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>CEP</label>
                                    <input type="number" class="form-control border-input" placeholder="Ex: 30450650" name="cep">
                                </div>
                            </div>
                        </div>
                        <div class="text-center ">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">Cadastrar</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>