<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Todos os locais</h4>
                </div>
                <div class="content">
                    <table id="locais" class="table table-hover display" style="width:100%">
                        <thead>
                        <tr>
                            <th hidden>#</th>
                            <th>Número</th>
                            <th>Município</th>
                            <th>CEP</th>
                        </tr>
                        </thead>
                        <tbody>

                        <?php foreach ($locais as $local) { ?>
                            <tr>
                                <td hidden><?= $local->getId(); ?></td>
                                <td><?= $local->getNumero(); ?></td>
                                <td><?= $local->getMunicipio(); ?></td>
                                <td><?= $local->getCEP(); ?></td>

                                <td>
                                    <a type="button"
                                       href="<?= $this->url('concedente', ['controller' => 'local', 'action' => 'editar', 'id' => $local->getId()]) ?>"
                                       class="btn btn-info btn-fill">
                                        <i class="fa fa-pencil" aria-hidden="true"></i>
                                    </a>

                                    <a href="<?= $this->url('concedente', ['controller' => 'local', 'action' => 'remover', 'id' => $local->getId()]) ?>"
                                       class="btn btn-danger btn-fill">
                                        <i class="fa fa-trash" aria-hidden="true" type="hidden"></i>
                                    </a>
                                </td>


                            </tr>

                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <?php echo $this->render("cadastrar.phtml");?>
    </div>
</div>
