<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('MyTree') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <?php
    $url = $this->url('investidor', ['controller' => 'cadastro', 'action' => 'cadastrar']);
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/form/main.css')
        ->prependStylesheet($this->basePath() . '/css/application/gaia.css')
        ->prependStylesheet($this->basePath() . '/css/form/util.css')
        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>
<nav class="navbar navbar-default navbar-transparent navbar-fixed-top" color-on-scroll="200">
    <!-- if you want to keep the navbar hidden you can add this class to the navbar "navbar-burger"-->
    <div class="container">
        <div class="navbar-header">
            <button id="menu-toggle" type="button" class="navbar-toggle" data-toggle="collapse" data-target="#example">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar bar1"></span>
                <span class="icon-bar bar2"></span>
                <span class="icon-bar bar3"></span>
            </button>
            <a href="<?= $this->url('application', array('action' => 'index')); ?>" class="navbar-brand">
                MyTree
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right navbar-uppercase">
                <li class="dropdown">
                <li>
                    <a href="<?= $this->url('application', array('controller' => 'Login', 'action' => 'index')); ?>">Login</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
</nav>

<div class="container-contact100">
    <div class="wrap-contact100">
        <div class="contact100-form-title"
             style="background-image: url('<?= $this->basePath() . '/img/application/header-1.jpeg'; ?>');">
				<span class="contact100-form-title-1">
					Cadastrar
				</span>

            <span class="contact100-form-title-2">
					Preencha com os seus dados!
				</span>
        </div>

        <?php
            echo $this->flashHelper();
        ?>

        <form class="contact100-form validate-form" action="<?= $url ?>" method="post">
            <div class="wrap-input100 validate-input" data-validate="Nome é obrigatório">
                <span class="label-input100">Nome:</span>
                <input class="input100" type="text" name="nome" placeholder="Insira o seu nome completo">
                <span class="focus-input100"></span>
            </div>

            <div class="wrap-input100 validate-input" data-validate="Email válido é obrigatório: ex@abc.xyz">
                <span class="label-input100">Email:</span>
                <input class="input100" type="email" name="email" placeholder="Insira um email válido">
                <span class="focus-input100"></span>
            </div>

            <div class="wrap-input100 validate-input" data-validate="Ramo é obrigatório">
                <span class="label-input100">Ramo:</span>
                <input class="input100" type="text" name="ramo" placeholder="Insira o seu ramo de atuação"
                       pattern="[a-zA-Z]*">
                <span class="focus-input100"></span>
            </div>

            <div class="wrap-input100 validate-input" data-validate="Celular é obrigatório">
                <span class="label-input100">Telefone:</span>
                <input class="input100" type="tel" data-mask="(00) 00000-0000" name="celular"
                       placeholder="Insira o número do seu celular" pattern=".{15}"
                       title="Insira um número de celular válido">
                <span class="focus-input100"></span>
            </div>

            <div class="wrap-input100 validate-input" data-validate="Senha é obrigatória">
                <span class="label-input100">Senha:</span>
                <input class="input100" type="password" name="senha" placeholder="Insira uma senha válida">
                <span class="focus-input100"></span>
            </div>

            <div class="container-contact100-form-btn">
                <button class="contact100-form-btn">
						<span>
							Submit
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
                </button>
            </div>
        </form>
    </div>
</div>

<div id="dropDownSelect1"></div>

<!-- More Scripts -->
<?php echo $this->inlineScript()
    ->prependFile($this->basePath() . '/js/form/main.js')
    ->prependFile($this->basePath() . '/js/form/jquery.mask.js')
    ->prependFile($this->basePath() . '/js/application/gaia.js')
    ->prependFile($this->basePath() . '/js/application/modernizr.js')
    ->prependFile($this->basePath() . '/js/bootstrap.js') ?>
</body>
</html>
