
<?php
    $url=$this->url("investidor", ['controller' => 'perfil', 'action' => 'editar']);
?>

<div class="container-fluid">
    <div class="row">
        
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Edit Profile</h4>
                </div>
                <div class="content">
                    <form method="post" action="<?= $url ?>">
                         <input type="hidden" value="<?= $investidor->getId(); ?>" name="id">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Nome:</label>
                                    <input type="text" class="form-control border-input" placeholder="Nome" name="nome"
                                           value="<?= $investidor->getNome(); ?>">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email address</label>
                                    <input type="email" name="email" class="form-control border-input" value="<?= $investidor->getEmail(); ?>" placeholder="Email">
                                </div>
                            </div>

                             <div class="col-md-5">
                                <div class="form-group">
                                    <label>Senha</label>
                                    <input type="password" class="form-control border-input" placeholder="Senha" name="senha"
                                           value="<?= $investidor->getSenha(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Ramo</label>
                                    <input type="text" class="form-control border-input" placeholder="Ramo" name="ramo" 
                                           value="<?= $investidor->getRamo(); ?>">
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">Atualizar Perfil</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>


    </div>
</div>