<div class="col-lg-12 col-md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Campanhas Finalizadas</h4>
    </div>
    <div class="content">

      <form method="post" action="<?= $url; ?>">
       <input type="hidden" value="" name="">
       <div class="row">
        <div class="col-md-12">
          <table id="campanhas" class="table table-hover display" style="width:100%">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Data Inicio</th>
                <th>Data Termino</th>
                <th>cidade</th>
                <th>UF</th>
                <th>CEP</th>
                <th hidden>idCampanha</th>
                <th>Qtd Mudas Liberadas</th>
                <th>Qtd de inscritos</th>
                <th>Qtd de Mudas Plantadas</th>
              </tr>
            </thead>

            <tbody>

              <?php foreach ($campanhas as $campanha) {
                if($campanha->getLocal()!=NULL){
                 ?>
                 <tr>
                   <td><?= $campanha->getNome(); ?></td>
                   <td><?= $campanha->getDataInicialString(); ?></td>
                   <td><?= $campanha->getDataFinalString(); ?></td>
                   <td><?= $campanha->getLocal()->getMunicipio(); ?></td>
                   <td><?= $campanha->getLocal()->getUf(); ?></td>
                   <td><?= $campanha->getLocal()->getCep(); ?></td>
                   <td hidden><?= $campanha->getId(); ?></td>
                   <td><?= $campanha->getEstoqueMuda()->getTotalMudasDisponibilizadas(); ?></td>
                   <td><?= $campanha->getEstoqueMuda()->totalPlantadoresInscritos(); ?></td>
                   
                   <?php 
                   if($campanha->getLocal()->qtdMudasPlantadas() !=0){
                     ?>
                     <td><?= $campanha->getLocal()->qtdMudasPlantadas(); ?></td>
                     <?php }else{ ?>
                     <td>0</td>
                     <?php }?>

                   </tr>
                   <?php }}?>

                 </tbody>
               </table>
             </div>
           </div>
           <div class="clearfix"></div>
         </form>
       </div>
     </div>
   </div>


   <script>
    jQuery(function ($) {
      $('#campanhas').DataTable( {

       "columnDefs": [

       {"className": "dt-center", "targets": "_all"}

       ],

     } );
    });
  </script>






