<?php
$url = $this->url('administrador', ['controller' => 'campanha', 'action' => 'index']);

?>

<div class="col-lg-12 col-md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Gerenciar Campanhas</h4>
    </div>
    <div class="content">
     <form method="post" action="<?= $url; ?>">
       <input type="hidden" value="" name="">

       <div class="row">
        <div class="col-md-12">
          <table id="campanhas" class="table table-hover display" style="width:100%">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Data Inicio</th>
                <th>Data Termino</th>
                <th>cidade</th>
                <th>UF</th>
                <th>CEP</th>
                <th hidden>idCampanha</th>
                <th>Acao</th>
                <th hidden>Tipos Muda</th>
              </tr>
            </thead>

            <tbody>

              <?php foreach ($campanhas as $campanha) {
                if($campanha->getLocal()!=NULL && $campanha->getDataFinal()>new \DateTime() && $campanha->getStatus()==NULL){
                 ?>
                 <tr>
                   <td><?= $campanha->getNome(); ?></td>
                   <td><?= $campanha->getDataIncialString(); ?></td>
                   <td><?= $campanha->getDataFinalString(); ?></td>
                   <td><?= $campanha->getLocal()->getMunicipio(); ?></td>
                   <td><?= $campanha->getLocal()->getUf(); ?></td>
                   <td><?= $campanha->getLocal()->getCep(); ?></td>
                   <td hidden><?= $campanha->getId(); ?></td>
                   <td>
                    <button type="button" data-toggle="modal" data-target="#modalLiberar" class="btn btn-info btn-fill">
                      <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>
                    </button>
                  </td>

                  <td hidden><?= $campanha->getLocal()->getMudasToString();?></td>
                  
                </tr>
                <?php }}?>

              </tbody>
            </table>
          </div>
        </div>
        <div class="clearfix"></div>
      </form>
    </div>
  </div>
</div>

<div id="modals">

 <div class="modal fade" id="modalLiberar" tabindex="-1" role="dialog" aria-labelledby=""
 aria-hidden="true">
 <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title text-center">Gerenciar Campanha</h4>
    </div>

    <div class="modal-body">
      <form method="post" action="<?= $this->url('administrador', ['controller'=>'campanha','action' => 'cancelar']) ?>"> 
        <input type="hidden" name="idCampanha" value="">

        <div class='form-group'>
          <input  class= 'btn btn-primary center-block' type='submit' value='Liberar Campanha'>
        </div>

      </div>
    </form>

    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
  </div>
</div>

</div>
</div>

<script>

  jQuery(function ($) {
    $('#campanhas').DataTable( {

     "columnDefs": [

     {"className": "dt-center", "targets": "_all"}

     ],
     

   } );
  });
</script>


<script>
  jQuery(function ($) {

   $("#modals").detach().appendTo('body');

   var table = $('#campanhas').DataTable();
   $('#campanhas tbody').on( 'click','tr' ,function () {

    var linhaSelecionada= table.row(this).index();
    var data = table.rows(linhaSelecionada).data();
    var infoCampanha=data[0];
    var nome=infoCampanha[0];
    //var dataInicio= infoCampanha[1];
    //var dataFinal= infoCampanha[2];
    //var cidade= infoCampanha[3];
    //var uf= infoCampanha[4];
    //var cep= infoCampanha[5];
    var idCampanha= infoCampanha[6];
    //var Tmudas=infoCampanha[7];
    //alert(Tmudas);

    $("input[name='idCampanha']").val(idCampanha);



    //var statusCampanha=infoCampanha[8];
    
    










  } );


 });


</script>

-->


