<?php
$url = $this->url('administrador', ['controller' => 'campanha', 'action' => 'index']);

?>

<div class="col-lg-12 col-md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Gerenciar Campanhas</h4>
    </div>
    <div class="content">

    <form method="post" action="<?= $url; ?>">
     <input type="hidden" value="" name="">
     <div class="row">
      <div class="col-md-12">
        <table id="campanhas" class="table table-hover display" style="width:100%">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Data Inicio</th>
              <th>Data Termino</th>
              <th>cidade</th>
              <th>UF</th>
              <th>CEP</th>
              <th hidden>idCampanha</th>
              <th>Acao</th>
              <th hidden>Tipos Muda</th>
            </tr>
          </thead>

          <tbody>

            <?php foreach ($campanhas as $campanha) {
              if($campanha->getLocal()!=NULL){
               ?>
               <tr>
                 <td><?= $campanha->getNome(); ?></td>
                 <td><?= $campanha->getDataInicialString(); ?></td>
                 <td><?= $campanha->getDataFinalString(); ?></td>
                 <td><?= $campanha->getLocal()->getMunicipio(); ?></td>
                 <td><?= $campanha->getLocal()->getUf(); ?></td>
                 <td><?= $campanha->getLocal()->getCep(); ?></td>
                 <td hidden><?= $campanha->getId(); ?></td>
                 <td>
                  <button type="button" data-toggle="modal" data-target="#modalLiberar" class="btn btn-info btn-fill">
                    <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>
                  </button>
                </td>

                <td hidden><?= $campanha->getLocal()->getMudasToString();?></td>

              </tr>
              <?php }}?>

            </tbody>
          </table>
        </div>
      </div>
      <div class="clearfix"></div>
    </form>
  </div>
</div>
</div>

<div id="modals">

 <div class="modal fade" id="modalLiberar" tabindex="-1" role="dialog" aria-labelledby=""
 aria-hidden="true">
 <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title text-center">Gerenciar Campanha</h4>
    </div>

    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#liberarCampanha">Liberar</a></li>
      <li><a data-toggle="tab" href="#cancelar">Cancelar</a></li>

    </ul>

    <div class="tab-content">
      <div id="liberarCampanha" class="tab-pane fade in active">


        <form method="post" action="<?= $this->url('administrador', ['controller'=>'campanha','action' => 'liberar']) ?>"> 
          <input type="hidden" name="idCampanhaLiberar">
          <input type="hidden" name="idTipoMuda">

          <div class='form-group'>
            <div class="row">

              <div class="col-md-3">
                <div class="form-group">
                  <label>Qtd de Mudas</label>
                  <input type="text" class="form-control border-input" name="qtdMudas" required>
                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label for="sel1">Tipos Muda</label>
                  <select required class="form-control border-input" id="sel1" name="tiposMuda" >

                  </select>
                </div>
              </div>

              <input  class= 'btn btn-primary center-block' type='submit' value='Liberar Campanha'>

            </div>

          </div>
        </form>

      </div>
      <div id="cancelar" class="tab-pane fade">

       <form method="post" action="<?= $this->url('administrador', ['controller'=>'campanha','action' => 'cancelar']) ?>"> 
        <input type="hidden" name="idCampanhaCancelar" value="">
        
        <label for="comment">Motivo de cancelamento:</label>
        
        <textarea class="form-control" rows="6" name="descricaoCancelamento" style="border:solid 1px black;" required></textarea>

        <input  class= 'btn btn-danger center-block' type='submit' value='Cancelar Campanha'>
      </form>
    </div>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
  </div>
</div>
</div>
</div>
</div>

<?php
echo $this->inlineScript()->prependFile($this->basePath() . '/js/Administrador/gerenciar.js');

?>

<script>

  jQuery(function ($) {
    $('#campanhas').DataTable( {

     "columnDefs": [

     {"className": "dt-center", "targets": "_all"}

     ],
     retrieve: true,
     

   } );
  });
</script>






