<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/form/form-labels-on-top.css') ?>

<form class="form-labels-on-top" method="post" action="#">

    <div class="form-title-row">
        <h1>Form Example</h1>
    </div>

    <div class="form-row">
        <label>
            <span>Full name</span>
            <input type="text" name="name">
        </label>
    </div>

    <div class="form-row">
        <label>
            <span>Email</span>
            <input type="email" name="email">
        </label>
    </div>

    <div class="form-row">
        <label>
            <span>Dropdown</span>
            <select name="dropdown">
                <option>Option One</option>
                <option>Option Two</option>
                <option>Option Three</option>
                <option>Option Four</option>
            </select>
        </label>
    </div>

    <div class="form-row">
        <label>
            <span>Checkbox</span>
            <input type="checkbox" name="checkbox" checked>
        </label>
    </div>

    <div class="form-row">
        <label><span>Radio</span></label>
        <div class="form-radio-buttons">

            <div>
                <label>
                    <input type="radio" name="radio">
                    <span>Radio option 1</span>
                </label>
            </div>

            <div>
                <label>
                    <input type="radio" name="radio">
                    <span>Radio option 2</span>
                </label>
            </div>

            <div>
                <label>
                    <input type="radio" name="radio">
                    <span>Radio option 3</span>
                </label>
            </div>

        </div>
    </div>

    <div class="form-row">
        <button type="submit">Submit Form</button>
    </div>

</form>