<?php
$url = $this->url('investidor', ['controller' => 'campanha', 'action' => 'cadastrar']);
?>


<div class="col-lg-12 col-md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Cadastrar Campanha</h4>
    </div>
    <div class="content">
     <form method="post" action="<?= $url; ?>">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Nome</label>
            <input type="text" class="form-control border-input" placeholder="Nome da Campanha" name="nome" required>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <label>Valor:</label>
            <input type="text" class="form-control border-input" placeholder="Valor para a Campanha" name="valor" required>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Data de Início da Campanha</label>
            <input type="text"
            class="form-control border-input validate-date"
            placeholder="Dia/Mês/Ano"
            data-mask="00/00/0000"
            name="dataInicio"
            
            oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
            oninput="setCustomValidity('')"
            required/>

          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <label>Data de Término da Campanha</label>
            <input type="text"
            class="form-control border-input validate-date"
            name="dataTermino"
            placeholder="Dia/Mês/Ano"
            data-mask="00/00/0000"
            oninvalid="this.setCustomValidity('Insira uma data válida no formato: Dia/Mês/Ano')"
            oninput="setCustomValidity('')"
            required/>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <table id="locais" class="table table-hover display" style="width:100%">
            <thead>
              <tr>
                <th></th>
                <th>Id</th>
                <th>Cidade</th>
                <th>UF</th>
                <th>Bairro</th>
                <th>CEP</th>
                <th>Detalhes</th>
                <th hidden>Complemento</th>
                <th hidden>Logradouro</th>
                <th hidden>Telefone concedente</th>
                <th hidden>Email concedente</th>
                <th hidden>Nome concedente</th>
                <th hidden>Espaço</th>
              </tr>
            </thead>

            <tbody>

              <?php foreach ($locais as $local ) { ?>

              <tr>

                <td>
                  <div class="radio">
                   <input class="input-radio" type="radio" name="local" />
                 </div>
               </td>
               <td><?= $local->getId(); ?></td>
               <td><?= $local->getMunicipio(); ?></td>
               <td><?= $local->getUF(); ?></td>
               <td><?= $local->getBairro(); ?></td>
               <td><?= $local->getCep(); ?></td>
               <td>
                <button type="button" data-toggle="modal" data-target="#detalhes-local" class="btn btn-info btn-fill">

                  <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>

                </button>
              </td>
              <td hidden><?= $local->getComplemento(); ?></td>
              <td hidden><?= $local->getLogradouro(); ?></td>
              <td hidden><?= $local->getConcedente()->getTelefone();?></td>
              <td hidden><?= $local->getConcedente()->getEmail();?></td>
              <td hidden><?= $local->getConcedente()->getNome();?></td>
              <td hidden><?= $local->getArea();?></td>
            </tr>
            <?php }?>
          </tbody>
        </table>
      </div>
    </div>

    <div class="row" style="display: none;">
      <div class="col-md-12">
        <div class="form-group">
          <input type="text" name="idLocal"/>
        </div>
      </div>
    </div>


    <div class="text-center ">
      <button type="submit" class="btn btn-info btn-fill btn-wd">Cadastrar</button>
    </div>
    <div class="clearfix"></div>
  </form>
</div>
</div>


<div id='modals'>

  <div id='detalhes-local' class='modal fade' role='dialog'>
   <div class='modal-dialog'>
     <div class='modal-content'>
       <div class='modal-header'>
         <button type='button' class='close' data-dismiss='modal'>&times;</button>;
         <h4 class='modal-title' align='center'>Dados do local</h4>
       </div>
       <div class='modal-body'>
         <p id="corpo"></p>
       </div>
       <div class='modal-footer'>
         <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
       </div>
     </div>
   </div>
 </div>
</div>


<?php
echo $this->inlineScript()->prependFile($this->basePath() . '/js/investidor/campanha/localDaCampanha.js');
echo $this->inlineScript()->prependFile($this->basePath() . '/js/investidor/campanha/dadosLocal.js');

?>

<script>
  jQuery(function ($) {
    $('#locais').DataTable( {

     "columnDefs": [

     {"className": "dt-center", "targets": "_all"}

     ],
     retrieve: true,

   } );
  });
</script>


