<?php

$url = $this->url('investidor', ['controller' => 'campanha', 'action' => 'editar']);

?>

<div class="col-lg-12 col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Dados do Local</h4>
        </div>
        <div class="content">
           <form method="post" action="<?= $url; ?>">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Logradouro</label>
                        <input type="text" class="form-control border-input" value="<?= $local->getLogradouro(); ?>" disabled>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label>Municipio:</label>
                        <input type="text" class="form-control border-input"  value="<?= $local->getMunicipio(); ?>" disabled>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <label>CEP:</label>
                    <input type="text" class="form-control border-input"  
                    value="<?= $local->getCep(); ?>" disabled>
                </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <label>Numero:</label>
                <input type="text" class="form-control border-input" 
                value="<?= $local->getNumero(); ?>" disabled>
            </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <label>Estado:</label>
            <input type="text" class="form-control border-input" 
             value="<?= $local->getUf(); ?>" disabled>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label>Complemento:</label>
            <input type="text" class="form-control border-input" 
             value="<?= $local->getComplemento(); ?>" disabled>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table id="locais" class="table table-hover display" style="width:100%">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Telefone</th>
                    <th>email</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><?= $local->getConcedente()->getNome(); ?></td>
                    <td><?= $local->getConcedente()->getTelefone();?></td>
                    <td><?= $local->getConcedente()->getEmail();?></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<div class="row" style="display: none;">
    <div class="col-md-12">
        <div class="form-group">
            <input type="text" name="idLocal" required/>
        </div>
    </div>
</div>

<div class="text-center ">
    <button type="submit" class="btn btn-info btn-fill btn-wd">Voltar</button>
</div>
<div class="clearfix"></div>
</form>
</div>
</div>
</div>

<?php
echo $this->inlineScript()
->prependFile($this->basePath() . '/js/datehelper.js');
?>


<script>
    jQuery(function ($) {
        $('#locais').DataTable( {
            columnDefs: [ {
                orderable: false,
                className: 'dt-center',
                targets:   0,
            } ],
            select: {
                style:    'os',
                selector: 'td:first-child'
            },
            order: [[ 1, 'asc' ]],
            paging:false,
            bFilter:false,

        } );

    });
</script>




