<?php
$url = $this->url('investidor', ['controller' => 'campanha', 'action' => 'cadastrar']);
?>

<div class="col-lg-12 col-md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Campanhas cadastradas</h4>
    </div>
    <div class="content">       
      <div class="row">
        <div class="col-md-12">
          <table id="locais" class="table table-hover display" style="width:100%">
            <thead>
              <tr>

                <th>Nome</th>
                <th>data Início</th>
                <th>data Término</th>
                <th>Cidade</th>
                <th>UF</th>
                <th>Status</th>
                <th hidden>Complemento</th>
                <th hidden>Logradouro</th>
                <th hidden>Cep</th>
                <th hidden>Bairro</th>
                <th hidden>Numero</th>
                <th hidden>Telefone concedente</th>
                <th hidden>Email concedente</th>
                <th hidden>Nome concedente</th>
                <th>Ação</th>
              </tr>
            </thead>

            <tbody>

              <?php foreach ($campanhas as $campanha) { ?>
              <tr>

                <td><?= $campanha->getNome(); ?></td>
                <td><?= $campanha->getDataInicialString(); ?></td>
                <td><?= $campanha->getDataFinalString(); ?></td>

                <?php if($campanha->getLocal()!=null) {?>
                <td><?= $campanha->getLocal()->getMunicipio(); ?></td> 
                <td><?= $campanha->getLocal()->getUF(); ?></td>

                <td hidden><?= $campanha->getLocal()->getComplemento(); ?></td>
                <td hidden><?= $campanha->getLocal()->getLogradouro(); ?></td>
                <td hidden><?= $campanha->getLocal()->getCep(); ?></td>
                <td hidden><?= $campanha->getLocal()->getBairro(); ?></td>
                <td hidden><?= $campanha->getLocal()->getNumero(); ?></td>
                <td hidden><?= $campanha->getLocal()->getConcedente()->getTelefone();?>
                </td>
                <td hidden><?= $campanha->getLocal()->getConcedente()->getEmail(); ?></td>
                <td hidden><?= $campanha->getLocal()->getConcedente()->getNome(); ?></td>

                <?php } else { ?>
                <td>-</td>
                <td>-</td>

                <td hidden></td>
                <td hidden></td>
                <td hidden></td>
                <td hidden></td>
                <td hidden></td>
                <td hidden></td>
                <td hidden></td>
                <td hidden></td>

                <?php } ?>


                <td>
                  <?php if($campanha->getEstadoCampanha()->getSituacaoCampanha()=="Aliberacao"){ ?>

                  <a href="#AguardandoLiberacao" data-toggle="modal"> 
                    <i class="fa fa-clock-o" aria-hidden="true"></i>
                  </a>  
                  
                  <?php } else if ($campanha->getEstadoCampanha()->getSituacaoCampanha()=="liberada") { ?> 
                  
                  <a href="#campanhaLiberada" data-toggle="modal">
                    <i class="fa fa-check text-success" aria-hidden="true"></i>
                  </a> 
                  
                  <?php } else if ($campanha->getEstadoCampanha()->getSituacaoCampanha()=="Alocal") { ?> 
                  
                  <a href="#AguardandoLocal" data-toggle="modal">
                    <i class="fa fa-home" aria-hidden="true"></i>
                  </a> 

                  <?php } else if ($campanha->getEstadoCampanha()->getSituacaoCampanha()=="abortada" && $campanha->getEstadoCampanha()->getMotivoAborto()!="" ) { ?>

                  <input type="hidden" id="mAborto" value="<?= $campanha->getEstadoCampanha()->getMotivoAborto();  ?>">

                  <a href="#motivoAborto" data-toggle="modal">
                    <i class="fa fa-ban" aria-hidden="true"></i>
                  </a> 

                  <?php } else if ($campanha->getEstadoCampanha()->getSituacaoCampanha()=="finalizada") { ?>

                  <a href="#campanhaFinalizada" data-toggle="modal">
                    <i class="fa fa-flag" aria-hidden="true"></i>
                  </a> 


                  <?php } else { ?>

                  <input type="hidden" id="motivoCancelamento" value="<?= $campanha->getEstadoCampanha()->getDescricaoCancelamento();  ?>">
                  <a href="#cancelamento" data-toggle="modal">
                    <i class="fa fa-times text-danger" aria-hidden="true"></i>
                  </a> 
                  <?php } ?>

                </td>
                <td>
                  <button type="button" data-toggle="modal" data-target="#detalhes-local" class="btn btn-info btn-fill">
                    <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>
                  </button>

                  <a href="<?= $this->url('investidor', [ 'controller'=>'campanha','action' => 'remover', 'id' => $campanha->getId()]) ?>"
                   class="btn btn-danger btn-fill"

                   <?php 
                   $situacao=$campanha->getEstadoCampanha()->getSituacaoCampanha();
                   if ($situacao=="liberada" ||$situacao=="finalizada" ) { ?>
                   disabled
                   <?php } ?>

                   >
                   <i class="fa fa-trash" aria-hidden="true" type="hidden"></i>
                 </a>

                 <a href="<?= $this->url('investidor', [ 'controller'=>'campanha','action' => 'editar', 'id' => $campanha->getId()]) ?>"
                  class="btn btn-warning btn-fill"

                  <?php 
                  $situacao=$campanha->getEstadoCampanha()->getSituacaoCampanha();
                  if ($situacao=="liberada" ||$situacao=="finalizada" ) { ?>
                  disabled
                  <?php } ?>
                  >
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                </a>
              </td>

            </tr>
            <?php }?>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

<div id="modals">

  <div id='detalhes-local' class='modal fade' role='dialog'>
   <div class='modal-dialog'>
     <div class='modal-content'>
       <div class='modal-header'>
         <button type='button' class='close' data-dismiss='modal'>&times;</button>
         <h4 class='modal-title' align='center'>Dados do local</h4>
       </div>

       <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#dadosLocal">Local</a></li>
        <li><a data-toggle="tab" href="#dadosConcedente">Concedente</a></li>
      </ul>

      <div class="tab-content">
        <div id="dadosLocal" class="tab-pane fade in active">
        </div>
        <div id="dadosConcedente" class="tab-pane fade">
        </div>
      </div>

      <div class='modal-footer'>
       <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
     </div>
   </div>
 </div>
</div>



<div id='campanhaLiberada' class='modal fade' role='dialog'>
 <div class='modal-dialog'>
   <div class='modal-content'>
     <div class='modal-header'>
       <button type='button' class='close' data-dismiss='modal'>&times;</button>
       <h4 class='modal-title' align='center'>Situação da campanha</h4>
     </div>
     <div class='modal-body'>
      <p>Campanha Liberada</p>
    </div>
    <div class='modal-footer'>
     <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
   </div>
 </div>
</div>
</div>


<div id='AguardandoLiberacao' class='modal fade' role='dialog'>
 <div class='modal-dialog'>
   <div class='modal-content'>
     <div class='modal-header'>
       <button type='button' class='close' data-dismiss='modal'>&times;</button>
       <h4 class='modal-title' align='center'>Situação da campanha</h4>
     </div>
     <div class='modal-body'>
      <p>Por favor, aguarde a liberação da campanha pela equipe My-Tree</p>
    </div>
    <div class='modal-footer'>
     <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
   </div>
 </div>
</div>
</div>



<div id='cancelamento' class='modal fade' role='dialog'>
 <div class='modal-dialog'>
   <div class='modal-content'>
     <div class='modal-header'>
       <button type='button' class='close' data-dismiss='modal'>&times;</button>
       <h4 class='modal-title' align='center'>Situação da campanha</h4>
     </div>
     <div class='modal-body'>
      <p>Campanha Cancelada</p><br>
      <p>Motivo Cancelamento:</p><br>
      <p id="corpoCancelamento"></p>

    </div>
    <div class='modal-footer'>
     <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
   </div>
 </div>
</div>
</div>

<div id='AguardandoLocal' class='modal fade' role='dialog'>
 <div class='modal-dialog'>
   <div class='modal-content'>
     <div class='modal-header'>
       <button type='button' class='close' data-dismiss='modal'>&times;</button>
       <h4 class='modal-title' align='center'>Situação da campanha</h4>
     </div>
     <div class='modal-body'>
      <p>Escolha um local para que a campanha seja liberada</p>
    </div>
    <div class='modal-footer'>
     <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
   </div>
 </div>
</div>
</div>


<div id='motivoAborto' class='modal fade' role='dialog'>
 <div class='modal-dialog'>
   <div class='modal-content'>
     <div class='modal-header'>
       <button type='button' class='close' data-dismiss='modal'>&times;</button>
       <h4 class='modal-title' align='center'>Situação da campanha</h4>
     </div>
     <div class='modal-body'>
      <p>A campanha foi abortada pelo seguinte motivo: </p>
      <p id='motivo'></p>
    </div>
    <div class='modal-footer'>
     <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
   </div>
 </div>
</div>
</div>



<div id='campanhaFinalizada' class='modal fade' role='dialog'>
 <div class='modal-dialog'>
   <div class='modal-content'>
     <div class='modal-header'>
       <button type='button' class='close' data-dismiss='modal'>&times;</button>
       <h4 class='modal-title' align='center'>Situação da campanha</h4>
     </div>
     <div class='modal-body'>
      <p>A campanha foi realizada</p>
    </div>
    <div class='modal-footer'>
     <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
   </div>
 </div>
</div>
</div>




</div>


<script>
  jQuery(function ($) {
    $('#locais').DataTable( {
      "columnDefs": [
      {"className": "dt-center", "targets": "_all"}
      ],
    });
  });
</script>


<script>
  jQuery(function ($) {
    var table = $('#locais').DataTable();
    $('#locais tbody').on( 'click', 'tr', function () {
      var linhaSelecionada= table.row(this).index();
      var data = table.rows(linhaSelecionada).data();
      $("#modals").detach().appendTo('body');
      var motivoAborto=$("#mAborto").val();
      $('#motivo').html(motivoAborto);
    });
  });
</script>



<script>
  jQuery(function ($) {
    var table = $('#locais').DataTable();
    $('#locais tbody').on( 'click', 'tr', function () {
      var linhaSelecionada= table.row(this).index();
      var data = table.rows(linhaSelecionada).data();
      $("#modals").detach().appendTo('body');
      var motivoCancelamento=$("#motivoCancelamento").val();
      $('#corpoCancelamento').html(motivoCancelamento);
    });
  });
</script>


<script>
 jQuery(function ($) {
   var table = $('#locais').DataTable();
   $('#locais tbody').on( 'click', 'tr', function () {
    var linhaSelecionada= table.row(this).index();
    var data = table.rows(linhaSelecionada).data();
    $("#modals").detach().appendTo('body');
    var infoLocal=data[0];
    var cadastroLocal;
    var cadastroConcedente;
    var cidade=infoLocal[3];
    if(cidade!="-"){
      var uf=infoLocal[4];
      var complemento= infoLocal[5];
      var logradouro=infoLocal[6];
      var cep= infoLocal[7];
      var bairro=infoLocal[8];
      var numero=infoLocal[9];
      var telConcedente=infoLocal[10];
      var emailConcedente=infoLocal[11];
      var nomeConcedente=infoLocal[12];
      cadastroLocal="Cidade: ";
      cadastroLocal+=cidade+"<br>";
      cadastroLocal+= "Estado: "
      cadastroLocal+=uf+"<br>";
      cadastroLocal+="Cep: ";
      cadastroLocal+=cep+"<br>";
      cadastroLocal+="Bairro: ";
      cadastroLocal+=bairro+"<br>";
      cadastroLocal+="Numero: ";
      cadastroLocal+=numero+"<br>";
      cadastroLocal+="Logradouro: ";
      cadastroLocal+=logradouro+"<br>";
      cadastroLocal+="Complemento: ";
      cadastroLocal+=complemento+"<br>";
      cadastroConcedente="Nome: ";
      cadastroConcedente+=nomeConcedente+"<br>";
      cadastroConcedente+="Telefone: ";
      cadastroConcedente+=telConcedente+"<br>";
      cadastroConcedente+="Email: ";
      cadastroConcedente+=emailConcedente+"<br>";
      $('#dadosLocal').html(cadastroLocal);
      $('#dadosConcedente').html(cadastroConcedente);
    } 
    else {
      cadastroLocal="<p align='center'> Nenhum local vinculado a campanha</p>"
    }
    $('#corpo').html(cadastro);
  } );
 });
</script>