<?php

$url = $this->url('investidor', ['controller' => 'campanha', 'action' => 'cadastrar']);

?>

<div class="col-lg-12 col-md-12">
    <div class="card">
        <div class="header">
            <h4 class="title">Campanhas cadastradas</h4>
        </div>
        <div class="content">       
            <div class="row">
                <div class="col-md-12">
                    <table id="locais" class="table table-hover display" style="width:100%">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th>data Início</th>
                                <th>data Término</th>
                                <th>Cidade</th>
                                <th>Estado</th>
                                <th hidden>Complemento</th>
                                <th hidden>Logradouro</th>
                                <th hidden>Cep</th>
                                <th hidden>Bairro</th>
                                <th hidden>Numero</th>
                                <th hidden>Telefone concedente</th>
                                <th hidden>Email concedente</th>
                                <th hidden>Nome concedente</th>
                                <th>Local</th>
                                <th>Ação</th>
                            </tr>
                        </thead>

                        <tbody>

                            <?php foreach ($campanhas as $campanha) { ?>
                            <tr>

                                <td><?= $campanha->getNome(); ?></td>
                                <td><?= $campanha->getDataIncialString(); ?></td>
                                <td><?= $campanha->getDataFinalString(); ?></td>
                                
                                <?php if($campanha->getLocal()!=null) {?>
                                <td><?= $campanha->getLocal()->getMunicipio(); ?></td> 
                                <td><?= $campanha->getLocal()->getUF(); ?></td>

                                <td hidden><?= $campanha->getLocal()->getComplemento(); ?></td>
                                <td hidden><?= $campanha->getLocal()->getLogradouro(); ?></td>
                                <td hidden><?= $campanha->getLocal()->getCep(); ?></td>
                                <td hidden><?= $campanha->getLocal()->getBairro(); ?></td>
                                <td hidden><?= $campanha->getLocal()->getNumero(); ?></td>
                                <td hidden><?= $campanha->getLocal()->getConcedente()->getTelefone();?></td>
                                <td hidden><?= $campanha->getLocal()->getConcedente()->getEmail(); ?></td>
                                <td hidden><?= $campanha->getLocal()->getConcedente()->getNome(); ?></td>

                                <?php }?>
                                <?php if($campanha->getLocal()==null) {?>                               
                                <td>-</td>
                                <td>-</td>
                                <td hidden></td>
                                <td hidden></td>
                                <td hidden></td>
                                <td hidden></td>
                                <td hidden></td>
                                <td hidden></td>
                                <td hidden></td>
                                <td hidden></td>
                                <?php }?>

                                <td>
                                    <button type="button" data-toggle="modal" data-target="#detalhes-local" class="btn btn-info btn-fill">>

                                        <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>
                                    </button>                                    

                                </td>
                                <td>
                                    <a href="<?= $this->url('investidor', [ 'controller'=>'campanha','action' => 'remover', 'id' => $campanha->getId()]) ?>"
                                       class="btn btn-danger btn-fill">
                                       <i class="fa fa-trash" aria-hidden="true" type="hidden"></i>
                                   </a>
                               </td>
                           </tr>
                           <?php }?>
                       </tbody>
                   </table>
               </div>
           </div>
       </div>
   </div>
</div>

<script>

    jQuery(function ($) {
        $('#locais').DataTable( {
            "columnDefs": [

            {"className": "dt-center", "targets": "_all"}

            ],
        });

    });
</script>

<script>

   jQuery(function ($) {
     var modal="<div id='detalhes-local' class='modal fade' role='dialog'>";
     modal+="<div class='modal-dialog'>";
     modal+="<div class='modal-content'>";
     modal+=" <div class='modal-header'>";
     modal+= "<button type='button' class='close' data-dismiss='modal'>&times;</button>";
     modal+="<h4 class='modal-title' align='center'>Dados do local</h4>";
     modal+="</div>";
     modal+="<div class='modal-body'>";
     modal+="<p id='corpo'></p>"
     modal+=" </div>";
     modal+="<div class='modal-footer'>";
     modal+="<button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>";
     modal+="</div>";
     modal+="</div>";
     modal+="</div>";
     modal+="</div>";
     $('body').append(modal);

     var table = $('#locais').DataTable();
     $('#locais tbody').on( 'click', 'tr', function () {
        var linhaSelecionada= table.row(this).index();
        var data = table.rows(linhaSelecionada).data();
        var infoLocal=data[0];
        var cadastro;
        var cidade=infoLocal[3];

        if(cidade!="-"){


            var uf=infoLocal[4];
            var complemento= infoLocal[5];
            var logradouro=infoLocal[6];
            var cep= infoLocal[7];
            var bairro=infoLocal[8];
            var numero=infoLocal[9];
            var telConcedente=infoLocal[10];
            var emailConcedente=infoLocal[11];
            var nomeConcedente=infoLocal[12];

            cadastro="Cidade: ";
            cadastro+=cidade+"<br>";
            cadastro+= "Estado: "
            cadastro+=uf+"<br>";
            cadastro+="Cep: ";
            cadastro+=cep+"<br>";
            cadastro+="Bairro: ";
            cadastro+=bairro+"<br>";
            cadastro+="Numero: ";
            cadastro+=numero+"<br>";

            cadastro+="Logradouro: ";
            cadastro+=logradouro+"<br>";
            cadastro+="Complemento: ";
            cadastro+=complemento+"<br>";
            cadastro+="<h4 class='modal-title' align='center'>Concedente</h4>";
            cadastro+="<hr>";
            cadastro+="Nome: ";
            cadastro+=nomeConcedente+"<br>";
            cadastro+="Telefone: ";
            cadastro+=telConcedente+"<br>";
            cadastro+="Email: ";
            cadastro+=emailConcedente+"<br>";
        } 

        else {
            cadastro="<p align='center'> Nenhum local vinculado a campanha</p>"
        }


        $('#corpo').html(cadastro);



    } );
 });
</script>

