<?php
$urlTipoMuda = $this->url('administrador', ['controller' => 'tipomuda', 'action' => 'cadastrar']);

?>

<div class="col-lg-12 col-md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Gerenciar Tipos de muda</h4>
    </div>
    <div class="content">

      <form method="post" action="<?= $urlTipoMuda; ?>">
       <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <label>Nome Popular</label>
            <input type="text" class="form-control border-input" name="nomePopular" placeholder="Nome Popular" required>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <label class>Nome Científico</label>
            <input type="text" class="form-control border-input" name="nomeCientifico" placeholder="Nome Científico" required>
          </div>
        </div>
      </div>

      <div class="text-center">
        <button type="submit" class="btn btn-info btn-fill btn-wd">Cadastrar</button>
      </div>
    </form>

    <div class="row">
      <div class="col-md-12">
        <table id="tiposmuda" class="table table-hover display" style="width:100%">
          <thead>
            <tr>
              <th>Nome Cientiico</th>
              <th>Nome Popular</th>

            </tr>
          </thead>
          <tbody>
            <?php foreach($tiposMuda as $tm) { ?>
            <tr>
              <td><?=$tm->getNomeCientifico(); ?></td>
              <td><?=$tm->getNomePopular(); ?></td>
            </tr>
            <?php } ?>
          </tbody>
        </table>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
</div>

<script>

  jQuery(function ($) {
    $('#tiposmuda').DataTable( {

     "columnDefs": [

     {"className": "dt-center", "targets": "_all"}

     ],
     retrieve: true,
     

   } );
  });
</script>