<?php
    $url = $this->url('plantador', ['controller' => 'perfil', 'action' => 'editar']);
?>


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Editar Perfil</h4>
                </div>
                <div class="content">
                    <form method="post" action="<?= $url; ?>">
                    <input type="hidden" value="<?= $plantador->getId(); ?>" name="id">
                        

                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Nome</label>
                                    <input type="text" class="form-control border-input" name="nome" placeholder="nome"
                                           value="<?= $plantador->getNome();?>">
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email
                                    </label>
                                    
                                    <input type="email" class="form-control border-input" name= "email" placeholder="Email" value="<?= $plantador->getEmail();?>">
                                </div>
                            </div>

                             <div class="col-md-5">
                                <div class="form-group">
                                    <label>Celular</label>
                                    <input type="text" class="form-control border-input" name="celular" placeholder="celular"
                                           value="<?= $plantador->getTelefone();?>">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Senha</label>
                                    <input type="password" class="form-control border-input" placeholder="Company"
                                           value="<?= $plantador->getSenha();?>" name="senha">
                                </div>
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">Atualizar Perfil</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>