<?php echo $this->headScript()->appendFile('https://maps.googleapis.com/maps/api/js'); ?>

<div class="container-fluid">
    <div class="card card-map">
        <div class="header">
            <h4 class="title">Google Maps</h4>
        </div>
        <div class="map">
            <div id="map"></div>
        </div>
    </div>
</div>

<script>
    $().ready(function(){
        demo.initGoogleMaps();
    });
</script>