<?php
$url = $this->url('investidor', ['controller' => 'campanha', 'action' => 'editar']);
?>

<div class="col-lg-12 col-md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Aderir a Campanha</h4>
    </div>
    <div class="content">
     <form method="post" action="<?= $url; ?>">
       <input type="hidden" value="" name="">

       <div class="row">
        <div class="col-md-12">
          <table id="campanhas" class="table table-hover display" style="width:100%">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Data Inicio</th>
                <th>Data Termino</th>
                <th>cidade</th>
                <th>UF</th>
                <th>CEP</th>
                <th hidden>idCampanha</th>
                <th hidden>situacao</th>
                <th>Detalhes</th>

              </tr>
            </thead>

            <tbody>
              <?php foreach ($campanhas as $campanha) {
                if($campanha->getLocal()!=NULL && $campanha->getDataFinal()>new \DateTime()){
                 ?>
                 <tr>
                   <td><?= $campanha->getNome(); ?></td>
                   <td><?= $campanha->getDataIncialString(); ?></td>
                   <td><?= $campanha->getDataFinalString(); ?></td>
                   <td><?= $campanha->getLocal()->getMunicipio(); ?></td>
                   <td><?= $campanha->getLocal()->getUf(); ?></td>
                   <td><?= $campanha->getLocal()->getCep(); ?></td>
                   <td hidden><?= $campanha->getId(); ?></td>
                   <td hidden><?= $plantador->isAderido($campanha); ?></td>
                   <td>
                    <button type="button" data-toggle="modal" data-target="#detalhes-local" class="btn btn-info btn-fill">

                      <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>

                    </button>
                  </td>
                </tr>
                <?php }}?>

              </tbody>
            </table>
          </div>
        </div>
        <div class="clearfix"></div>
      </form>
    </div>
  </div>
</div>

<script>
  jQuery(function ($) {
    $('#campanhas').DataTable( {

     "columnDefs": [

     {"className": "dt-center", "targets": "_all"}

     ],

   } );
  });
</script>

<script>
  jQuery(function ($) {
   var modal="<div id='detalhes-local' class='modal fade' role='dialog'>";
   modal+="<div class='modal-dialog'>";
   modal+="<div class='modal-content'>";
   modal+=" <div class='modal-header'>";
   modal+= "<button type='button' class='close' data-dismiss='modal'>&times;</button>";
   modal+="<h4 class='modal-title' align='center'>Informações da Campanha</h4>";
   modal+="</div>";
   modal+="<div class='modal-body'>";
   modal+="<p id='corpo'></p>"
   modal+=" </div>";
   modal+="<div class='modal-footer'>";
   modal+="<button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>";
   modal+="</div>";
   modal+="</div>";
   modal+="</div>";
   modal+="</div>";
   $('body').append(modal);


   var table = $('#campanhas').DataTable();
   $('#campanhas tbody').on( 'click', 'tr', function () {
    var linhaSelecionada= table.row(this).index();
    var data = table.rows(linhaSelecionada).data();
    var infoCampanha=data[0];
    var nome=infoCampanha[0];
    var dataInicio= infoCampanha[1];
    var dataFinal= infoCampanha[2];
    var cidade= infoCampanha[3];
    var uf= infoCampanha[4];
    var cep= infoCampanha[5];
    var idCampanha= infoCampanha[6];
    var isAderido= infoCampanha[7];
  
    var campanha="Nome: ";
    campanha+=nome+"<br>";
    campanha+= "Data inicio: "
    campanha+=dataInicio+"<br>";
    campanha+="Data Final: ";
    campanha+=dataFinal+"<br>";
    campanha+="Cidade: ";
    campanha+=cidade+"<br>";
    campanha+="UF: ";
    campanha+=uf+"<br>";
    campanha+="Cep: ";
    campanha+=cep+"<br>";


    if(!isAderido){
      campanha+="<form method='post' action='<?= $this->url('plantador', [ 'controller'=>'campanha','action' =>'aderir'])?>'>";
      campanha+="<input type='hidden' value='"+idCampanha+"' name='id'>";
      campanha+="<div class='form-group'>"
      campanha+="<input  class= 'btn btn-primary center-block' type='submit' value='aderir'>";
      campanha+="</div>"
      campanha+="</fom>";

    }else {
     campanha+="<form method='post' action='<?= $this->url('plantador', [ 'controller'=>'campanha','action' =>'sair'])?>'>";
     campanha+="<input type='hidden' value='"+idCampanha+"' name='id'>";
     campanha+="<div class='form-group'>"
     campanha+="<input  class= 'btn btn-danger center-block' type='submit' value='sair'>";
     campanha+="</div>"
     campanha+="</fom>";

   }

   $('#corpo').html(campanha);
 } );


 });


</script>