<?php
$url = $this->url('investidor', ['controller' => 'campanha', 'action' => 'editar']);
?>

<div class="col-lg-12 col-md-12">
  <div class="card">
    <div class="header">
      <h4 class="title">Histórico de campanhas</h4>
    </div>
    <div class="content">
     <form method="post" action="<?= $url; ?>">
       <input type="hidden" value="" name="">

       <div class="row">
        <div class="col-md-12">
          <table id="campanhas" class="table table-hover display" style="width:100%">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Data Inicio</th>
                <th>Data Termino</th>
                <th>Cidade</th>
                <th>UF</th>
                <th>CEP</th>
                <th>Aderiu</th>
                <th hidden>aderiu-sort</th>
                <th hidden>situacao</th>
                <th hidden>idCampanha</th>
                <th>Ação</th>


              </tr>
            </thead>

            <tbody>
              <?php foreach ($campanhas as $campanha) {?>
              <tr>
               <td><?= $campanha->getNome(); ?></td>
               <td><?= $campanha->getDataInicialString(); ?></td>
               <td><?= $campanha->getDataFinalString(); ?></td>
               <td><?= $campanha->getLocal()->getMunicipio(); ?></td>
               <td><?= $campanha->getLocal()->getUf(); ?></td>
               <td><?= $campanha->getLocal()->getCep(); ?></td>
               <td>

                 <?php if($plantador->isAderido($campanha) && $campanha->getEstadoCampanha()->getSituacaoCampanha()=="abortada"){ ?>

                    <i class="fa fa-times text-danger" aria-hidden="true"></i>

                 <?php }else if($plantador->isAderido($campanha)){ ?>
                  <i class="fa fa-check text-success"  aria-hidden="true"></i>

                 <?php } else {?>
                 <i class="fa fa-sign-in" aria-hidden="true"></i>

                 <?php } ?>
               </td>

               <td hidden>
                 <?php if($plantador->isAderido($campanha)){ ?>
                 1
                 <?php } else {?>
                 0
                 <?php } ?>
               </td>

               <td hidden><?= $plantador->isAderido($campanha); ?></td>
               <td hidden><?= $campanha->getId(); ?></td>
               <td>
                <button type="button" data-toggle="modal" data-target="#detalhes-local" class="btn btn-info btn-fill">

                  <i class="glyphicon glyphicon-plus" aria-hidden="true"></i>

                </button>
              </td>
            </tr>
            <?php }?>

          </tbody>
        </table>
      </div>
    </div>
    <div class="clearfix"></div>
  </form>
</div>
</div>
</div>

<script>
  jQuery(function ($) {
    $('#campanhas').DataTable( {
      columnDefs: [
      {targets: '_all', className: 'dt-center'},
      { "orderable": false, "targets": [ 1, 2 ] },
      { "orderData":[ 7 ],   "targets": [ 6 ] },
      ],
      order: [[6, 'desc']],
      paging:false,
    });
  });
</script>


<div id="modals">

  <div id='detalhes-local' class='modal fade' role='dialog'>
   <div class='modal-dialog'>
     <div class='modal-content'>
       <div class='modal-header'>
         <button type='button' class='close' data-dismiss='modal'>&times;</button>
         <h4 class='modal-title' align='center'>Informações da Campanha</h4>
       </div>
       <div class='modal-body'>
         <p id='corpo'></p>
       </div>
       <div class='modal-footer'>
         <button type='button' class='btn btn-default' data-dismiss='modal'>Fechar</button>
       </div>
     </div>
   </div>
 </div>
 
</div>


<script>
  jQuery(function ($) {
   var table = $('#campanhas').DataTable();
   $('#campanhas tbody').on( 'click', 'tr', function () {
    var linhaSelecionada= table.row(this).index();
    var data = table.rows(linhaSelecionada).data();
    
    $("#modals").detach().appendTo('body');
    var infoCampanha=data[0];
    var nome=infoCampanha[0];
    var dataInicio= infoCampanha[1];
    var dataFinal= infoCampanha[2];
    var cidade= infoCampanha[3];
    var uf= infoCampanha[4];
    var cep= infoCampanha[5];
    var idCampanha= infoCampanha[9];
    var isAderido= infoCampanha[8];
    
    var campanha="Nome: ";
    campanha+=nome+"<br>";
    campanha+= "Data inicio: ";
    campanha+=dataInicio+"<br>";
    campanha+="Data Final: ";
    campanha+=dataFinal+"<br>";
    campanha+="Cidade: ";
    campanha+=cidade+"<br>";
    campanha+="UF: ";
    campanha+=uf+"<br>";
    campanha+="Cep: ";
    campanha+=cep+"<br>";
    
    if(!isAderido){
      campanha+="<form method='post' action='<?= $this->url('plantador', [ 'controller'=>'campanha','action' =>'aderir'])?>'>";
      campanha+="<input type='hidden' value='"+idCampanha+"' name='id'>";
      campanha+="<div class='form-group'>";
      campanha+="<input  class= 'btn btn-primary center-block' type='submit' value='aderir'>";
      campanha+="</div>";
      campanha+="</form>";

    }else {
     campanha+="<form method='post' action='<?= $this->url('plantador', [ 'controller'=>'campanha','action' =>'sair'])?>'>";
     campanha+="<input type='hidden' value='"+idCampanha+"' name='id'>";
     campanha+="<div class='form-group'>";
     campanha+="<input  class= 'btn btn-danger center-block' type='submit' value='sair'>";
     campanha+="</div>";
     campanha+="</form>";
   }
   $('#corpo').html(campanha);
 } );


 });
</script>
