<?php    
$url = $this->url('concedente', ['controller' => 'perfil', 'action' => 'editar']);
?>


<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Editar Perfil</h4>
                </div>
                <div class="content">
                    <form method="" action="<?= $url;?>">
                        <input type="hidden" value="<?= $concedente->getId(); ?>" name="id">

                        <div class="row">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <label>Nome</label>
                                    <input type="text" class="form-control border-input" placeholder="Username" value="<?= $concedente->getNome();?>" >
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email address</label>
                                    <input type="email" class="form-control border-input" placeholder="Email" name="email" value="<?= $concedente->getEmail(); ?>">
                                </div>
                            </div>

                            <div class="col-md-5">
                                <div class="form-group">
                                    <label>Celular</label>
                                    <input type="text" class="form-control border-input" placeholder="Celular" name="celular"
                                    value="<?= $concedente->getTelefone(); ?>">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Senha</label>
                                    <input type="password" class="form-control border-input" placeholder="senha" name="senha"
                                    value= "<?= $concedente->getSenha();?>">
                                </div>
                            </div>
                        </div>

                        <div class="text-center">
                            <button type="submit" class="btn btn-info btn-fill btn-wd">Atualizar Perfil</button>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
