<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('MyTree') ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/form/main.css')
        ->prependStylesheet($this->basePath() . '/css/form/util.css')
        ->prependStylesheet($this->basePath() . '/css/form/daterangepicker.css')
        ->prependStylesheet($this->basePath() . '/css/form/select2.min.css')
        ->prependStylesheet($this->basePath() . '/css/form/animsition.min.css')
        ->prependStylesheet($this->basePath() . '/css/form/hamburgers.min.css')
        ->prependStylesheet($this->basePath() . '/css/animate.min.css')
        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

</head>
<body>
<div class="container-contact100">
    <div class="wrap-contact100">
        <div class="contact100-form-title"
             style="background-image: url('<?= $this->basePath() . '/img/application/header-1.jpeg'; ?>');">
				<span class="contact100-form-title-1">
					Cadastrar
				</span>

            <span class="contact100-form-title-2">
					Preencha com os seus dados!
				</span>
        </div>

        <form class="contact100-form validate-form">
            <div class="wrap-input100 validate-input" data-validate="Nome é obrigatório">
                <span class="label-input100">Nome:</span>
                <input class="input100" type="text" name="name" placeholder="Enter full name">
                <span class="focus-input100"></span>
            </div>

            <div class="wrap-input100 validate-input" data-validate="Email válido é obrigatório: ex@abc.xyz">
                <span class="label-input100">Email:</span>
                <input class="input100" type="text" name="email" placeholder="Enter email addess">
                <span class="focus-input100"></span>
            </div>

            <div class="wrap-input100 validate-input" data-validate="Celular é obrigatório">
                <span class="label-input100">Celular:</span>
                <input class="input100" type="text" name="phone" placeholder="Enter phone number">
                <span class="focus-input100"></span>
            </div>

            <div class="container-contact100-form-btn">
                <button class="contact100-form-btn">
						<span>
							Submit
							<i class="fa fa-long-arrow-right m-l-7" aria-hidden="true"></i>
						</span>
                </button>
            </div>
        </form>
    </div>
</div>

<div id="dropDownSelect1"></div>

<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/form/main.js')
    ->prependFile($this->basePath() . '/js/form/countdowntime.js')
    ->prependFile($this->basePath() . '/js/form/daterangepicker.js')
    ->prependFile($this->basePath() . '/js/form/moment.min.js')
    ->prependFile($this->basePath() . '/js/form/select2.min.js')
    ->prependFile($this->basePath() . '/js/bootstrap.js')
    ->prependFile($this->basePath() . '/js/form/popper.min.js')
    ->prependFile($this->basePath() . '/js/form/animsition.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
</body>
</html>
