<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('MyTree - Investidor') ?>

    <?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet('https://fonts.googleapis.com/css?family=Muli:400,300')
    ->prependStylesheet($this->basePath() . '/css/paper-dashboard/themify-icons.css')
    ->prependStylesheet($this->basePath() . '/css/paper-dashboard/paper-dashboard.css')
    ->prependStylesheet($this->basePath() . '/css/data-tables/jquery.dataTables.min.css')
        //->prependStylesheet($this->basePath() . '/css/data-tables/select.dataTables.min.css')
    ->prependStylesheet($this->basePath() . '/css/vendor/font-awesome.min.css')
    ->prependStylesheet($this->basePath() . '/css/animate.min.css')
    ->prependStylesheet($this->basePath() . '/css/vendor/bootstrap.min.css') 
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/vendor/jquery.min.js')
    ->prependFile($this->basePath() . '/js/vendor/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/vendor/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>

</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-background-color="black" data-active-color="danger">

        <!--
            Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
            Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
        -->

        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="http://www.creative-tim.com" class="simple-text">
                    MyTree
                </a>
            </div>

            <ul class="nav">
                <li class="dashboard aba">
                    <a href="<?= $this->url('investidor', array('controller' => 'dashboard', 'action' => 'index')); ?>">
                        <i class="ti-panel"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="perfil aba">
                    <a href="<?= $this->url('investidor', array('controller' => 'perfil', 'action' => 'index')); ?>">
                        <i class="ti-user"></i>
                        <p>Perfil do Usuário</p>
                    </a>
                </li>

                <li class="mapa aba">
                    <a href="<?= $this->url('investidor', array('controller' => 'campanha', 'action' => 'cadastrar')); ?>">
                        <i class="ti-map"></i>
                        <p>Cadastrar Campanha</p>
                    </a>
                </li>

                <li class="mapa aba">
                    <a href="<?= $this->url('investidor', array('controller' => 'campanha', 'action' => 'index')); ?>">
                        <i class="ti-map"></i>
                        <p>Gerenciar Campanha</p>
                    </a>
                </li>

                <li class="mapa aba">
                    <a href="<?= $this->url('investidor', array('controller' => 'mapa', 'action' => 'index')); ?>">
                        <i class="ti-map"></i>
                        <p>Mapa</p>
                    </a>
                </li>
                <li class="active-pro">
                    <a href="<?= $this->url('application', array('controller' => 'login', 'action' => 'logout')); ?>">
                        <i class="ti-power-off"></i>
                        <p>Sair</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Dashboard</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="ti-panel"></i>
                                <p>Stats</p>
                            </a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="ti-bell"></i>
                                <p class="notification">5</p>
                                <p>Notifications</p>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Notification 1</a></li>
                                <li><a href="#">Notification 2</a></li>
                                <li><a href="#">Notification 3</a></li>
                                <li><a href="#">Notification 4</a></li>
                                <li><a href="#">Another notification</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="#">
                                <i class="ti-settings"></i>
                                <p>Settings</p>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        <div class="content">
            <?php echo $this->content; ?>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                        <li>
                            <a href="http://www.creative-tim.com">
                                Creative Tim
                            </a>
                        </li>
                        <li>
                            <a href="http://blog.creative-tim.com">
                                Blog
                            </a>
                        </li>
                        <li>
                            <a href="http://www.creative-tim.com/license">
                                Licenses
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright pull-right">
                    &copy;
                    <script>document.write(new Date().getFullYear())</script>
                    , made with <i class="fa fa-heart heart"></i> by <a href="http://www.creative-tim.com">Creative
                    Tim</a>
                </div>
            </div>
        </footer>
    </div>
</div>

<!-- More Scripts -->
<?php echo $this->inlineScript()
->prependFile($this->basePath() . '/js/style.js')
->prependFile($this->basePath() . '/js/data-tables/jquery.js')
->prependFile($this->basePath() . '/js/paper-dashboard/demo.js')
->prependFile($this->basePath() . '/js/paper-dashboard/paper-dashboard.js')
->prependFile($this->basePath() . '/js/paper-dashboard/bootstrap-notify.js')
->prependFile($this->basePath() . '/js/paper-dashboard/chartist.min.js')
->prependFile($this->basePath() . '/js/paper-dashboard/bootstrap-checkbox-radio.js')
->prependFile($this->basePath() . '/js/data-tables/dataTables.select.min.js')
->prependFile($this->basePath() . '/js/data-tables/jquery.dataTables.min.js')
->prependFile($this->basePath() . '/js/data-tables/dataTables.fixedHeader.min.js')
->prependFile($this->basePath() . '/js/vendor/bootstrap.min.js') ?>
</body>
<!-- Modal -->

</html>
