<div class="section section-our-team-freebie">
    <div class="parallax filter filter-color-black">
        <div class="image" style="background-image:url('<?= $this->basePath() . '/img/application/header-2.jpeg'; ?>')">
        </div>
        <div class="container">
            <div class="content">
                <div class="row">
                    <div class="title-area">
                        <h2>Cadastro</h2>
                        <div class="separator separator-danger">✻</div>
                        <p class="description">Nos conte um pouco sobre você para iniciarmos a nossa jornada em prol de um mundo mais sustentável e verde.</p>
                    </div>
                </div>

                <div class="team">
                    <div class="row">
                        <div class="col-md-10 col-md-offset-1">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="card card-member">
                                        <div class="content">
                                            <div class="avatar avatar-danger">
                                                <img alt="..." class="img-circle"
                                                     src="<?= $this->basePath() . '/img/application/faces/face_1.jpg'; ?>"/>
                                            </div>
                                            <div class="description">
                                                <h3 class="title">Plantador</h3>
                                                <p class="small-text">Quero Plantar</p>
                                                <p class="description">Tem uma vontade enorme de plantar uma muda e vê-la crescer? Vamos por aqui!</p>
                                                <div class="button-get-started">
                                                    <a href="<?= $this->url('pessoa', ['controller' => 'cadastro', 'action' => 'index']); ?>" class="btn btn-sucess btn-fill btn-lg">Cadastrar</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="card card-member">
                                        <div class="content">
                                            <div class="avatar avatar-danger">
                                                <img alt="..." class="img-circle"
                                                     src="<?= $this->basePath() . '/img/application/faces/face_4.jpg'; ?>"/>
                                            </div>
                                            <div class="description">
                                                <h3 class="title">Concedente</h3>
                                                <p class="small-text">Tenho Espaço</p>
                                                <p class="description">Possui espaço disponível para reflorestamento e quer fazer o bem? Clica aí!</p>
                                                <div class="button-get-started">
                                                    <a href="<?= $this->url('concedente', ['controller' => 'cadastro', 'action' => 'index']); ?>" class="btn btn-sucess btn-fill btn-lg">Cadastrar</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="card card-member">
                                        <div class="content">
                                            <div class="avatar avatar-danger">
                                                <img alt="..." class="img-circle"
                                                     src="<?= $this->basePath() . '/img/application/faces/face_3.jpg'; ?>"/>
                                            </div>
                                            <div class="description">
                                                <h3 class="title">Investidor</h3>
                                                <p class="small-text">Quero Investir</p>
                                                <p class="description">Quer associar a sua marca a campanhas de reflorestamento? Comece aqui!</p>
                                                <div class="button-get-started">
                                                    <a href="<?= $this->url('investidor', ['controller'=>'cadastro', 'action'=>'index']) ?>" class="btn btn-sucess btn-fill btn-lg">Cadastrar</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>